'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',calendar:'M8 2v4 M16 2v4 M3 9h18 M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z M7 13h2 M12 13h2 M7 17h2',chart:'M4 20V10 M10 20V4 M16 20v-7 M3 21h18',document:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z M14 2v6h6 M8 12h8 M8 16h6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8z M10 2h4l1 3 3 1 3-1 2 4-2 2v3l2 2-2 4-3-1-3 1-1 3h-4l-1-3-3-1-3 1-2-4 2-2v-3l-2-2 2-4 3 1 3-1z',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M12 7v5l3 2',arrow:'M5 12h14 M14 7l5 5-5 5',check:'M5 12l4 4L19 6',spark:'M12 2l3 7 7 3-7 3-3 7-3-7-7-3 7-3z',alert:'M12 3L2 21h20z M12 9v5 M12 18h.01',book:'M3 4h7a2 2 0 0 1 2 2v15a3 3 0 0 0-3-2H3z M21 4h-7a2 2 0 0 0-2 2v15a3 3 0 0 1 3-2h6z',racket:'M13 3c4-2 8 1 7 5s-5 8-9 7-6-5-4-8 4-4 6-4z M9 14l-6 7 M4 18l2 2 M8 5l9 9 M12 3l8 7 M7 9l6 6 M9 4l-2 7 M14 3l-5 11 M18 5l-5 10',pen:'M16 3l5 5-12 12H3v-6z M13 6l5 5',film:'M3 3h18v18H3z M8 3v18 M16 3v18 M3 8h5 M3 16h5 M16 8h5 M16 16h5',sales:'M3 7h18v14H3z M8 7V3h8v4 M3 12h18 M10 12v3h4v-3',teach:'M3 4h18v13H3z M12 17v4 M8 21h8 M7 8h10 M7 12h6',camera:'M3 7h4l2-3h6l2 3h4v14H3z M12 10a4 4 0 1 0 0 8 4 4 0 0 0 0-8z',box:'M12 2l9 5v10l-9 5-9-5V7z M3 7l9 5 9-5 M12 12v10 M7 4l10 6',play:'M7 3l14 9-14 9z',pause:'M7 4v16 M17 4v16',copy:'M9 8h12v14H9z M4 16H2V2h12v3',send:'M22 2L9 15 M22 2l-7 20-6-7-7-6z',refresh:'M21 3v6h-6 M3 21v-6h6 M21 9a9 9 0 0 0-15-5 M3 15a9 9 0 0 0 15 5'};
const icon=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.document}"/></svg>`;
const cats={'IELTS':'book','Cầu lông':'racket','Content':'pen','Edit':'film','Bán hàng':'sales','Dạy':'teach','Quay 100 source':'camera','Tạo dịch vụ gói gọn':'box','Livestream':'play'};
const labels={sent:'Đã có đề',ready:'Đang chuẩn bị',graded:'Đã chấm đủ',needs_evidence:'Cần bằng chứng',delivery_error:'Gửi chưa xong',planned:'Chưa đến lượt',queued:'Chờ chấm',analyzing:'Đang phân tích',failed:'Cần thử lại'};
const pageNames={overview:'Tổng quan',roadmap:'Lộ trình mỗi ngày',progress:'Tiến bộ của tôi',samples:'Đề mẫu để duyệt',batches:'Bộ bài & chấm',settings:'Cài đặt kết nối'};
let state=null, sampleData=[],page='overview',selectedDate='',sampleIndex=0,filter='Tất cả',task=null,modalTab='assignment',uploaded=[];
let rendering=false,toastTimer=null,health={online:false},lastFingerprint='',modalPreviousFocus=null;
async function api(path,data){
  const options=data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Coach-Request':'1'},body:JSON.stringify(data)};
  const res=await fetch(path,options); const body=await res.json();
  if(!res.ok)throw new Error(body.error||'Không hoàn thành yêu cầu.'); return body;
}
function toast(message,error=false){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').className='show'+(error?' error':'');toastTimer=setTimeout(()=>$('#toast').className='',6000);}
const time=t=>t?new Date(t*1000).toLocaleTimeString('vi-VN',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit'}):'—';
const dateLabel=d=>{if(!d)return '';const [y,m,day]=d.split('-');return `${day}.${m}.${y}`;};
const status=s=>`<span class="status ${esc(s)}">${s==='graded'?icon('check'):''}${esc(labels[s]||s)}</span>`;
function heading(title,subtitle,tools='',kicker='MỖI GIỜ, MỘT BƯỚC TIẾN'){return `<div class="page-heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p class="subtitle">${subtitle}</p></div><div class="heading-tools">${tools}</div></div>`;}
const datePicker=()=>`<input type="date" class="date-input" id="date-picker" aria-label="Ngày xem lộ trình" value="${esc(state.date)}"><button class="btn small" data-action="today">Hôm nay</button>`;
function setupNotice(){
 const c=state.settings;let title,text,target='settings',action='';
 if(!health.online){title='Bước 1 · Kết nối AI';text='Vào Cài đặt kết nối và kiểm tra Codex trước khi bắt đầu.';}
 else if(!c.approved){title='Bước 2 · Xem và duyệt đề mẫu';text='Kiểm tra đề, biểu đồ và đáp án đầy đủ. Duyệt mẫu để bắt đầu lịch tại mốc đầu giờ kế tiếp.';target='samples';}
 else if(!c.active){title='Bước 3 · Bật lịch mỗi giờ';text='Đề được lưu trong app vào các mốc giờ đúng. Bạn làm, nộp và xem chấm bài trên laptop; Telegram chỉ là thông báo tùy chọn.';action='toggle';}
 else return '';
 return `<div class="notice">${icon('arrow')}<div><strong>${title}</strong><br>${text}</div><div class="notice-actions"><button class="btn primary small" ${action?`data-action="${action}"`:`data-page="${target}"`}>${action?'Bật tạo đề tự động':'Mở bước này'}</button></div></div>`;
}
function failureNotice(){
  if(!state.failures.length&&!state.delivery_issues.length&&!state.poll_error)return '';
  const msg=state.failures[0]?.error||state.delivery_issues[0]?.error||state.poll_error;
  const uncertain=state.delivery_issues.some(i=>i.status==='uncertain');
  return `<div class="notice error">${icon('alert')}<div><strong>Có tác vụ cần kiểm tra</strong><br>${esc(msg)}</div><div class="notice-actions"><button class="btn small" data-action="retry">${icon('refresh')}Thử lại</button>${uncertain?'<button class="btn small danger" data-action="retry-uncertain">Gửi lại tin chưa xác định</button>':''}</div></div>`;
}
function statsCards(){const s=state.stats; return `<div class="stats-grid">
  <div class="stat-card"><div class="stat-top">Bài hoàn thành<span class="stat-icon">${icon('check')}</span></div><div class="stat-value">${s.completed}<span>/ 24</span></div><div class="stat-note">Đã chấm đủ các tiêu chí</div></div>
  <div class="stat-card"><div class="stat-top">Điểm trung bình<span class="stat-icon">${icon('chart')}</span></div><div class="stat-value">${s.average??'—'}<span>/ 100</span></div><div class="stat-note">${s.average===null?'Bắt đầu từ bài nộp đầu tiên':'Điểm AI và phần người dùng xác minh'}</div></div>
  <div class="stat-card"><div class="stat-top">Tiến bộ đo được<span class="stat-icon">${icon('spark')}</span></div><div class="stat-value">${s.growth===null?'—':(s.growth>0?'+':'')+s.growth}<span>${s.growth===null?'':'%'}</span></div><div class="stat-note">${s.growth===null?'Cần thêm bài cùng chuẩn':`So với ${dateLabel(s.baseline_day)}`}<span class="mini-tag">Mục tiêu +10%</span></div></div>
  <div class="stat-card"><div class="stat-top">Độ khó hiện tại<span class="stat-icon">${icon('document')}</span></div><div class="stat-value">${state.settings.level.toFixed(2)}<span>×</span></div><div class="stat-note">+10% khi đủ 24 bài, TB ≥ 80</div></div></div>`;}
function skillList(){const groups=state.stats.skills;return `<div class="skill-list">${Object.keys(cats).map(c=>{const vals=Object.entries(groups).filter(([key])=>key===c||key.startsWith(c+' · ')).map(([,v])=>v);const avg=vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):null;return `<div class="skill-row"><div class="skill-label"><span>${esc(c)}</span><b>${avg===null?'Chưa có điểm':avg+'/100'}</b></div><div class="skill-track"><div class="skill-fill" style="--width:${avg??0}%"></div></div></div>`;}).join('')}</div>`;}
function taskRows(tasks,planned=true){if(!tasks.length&&planned){return state.schedule.slice(0,4).map(s=>`<div class="task-row" data-page="samples"><span class="time">#${String(s.slot).padStart(2,'0')}</span><div class="task-name"><span class="category-icon">${icon(cats[s.category])}</span><div><strong>${esc(s.category)}${s.skill?' · '+esc(s.skill):''}</strong><small>Đề thực sẽ được tạo bằng nguồn AI bạn đã chọn</small></div></div>${status('planned')}<span class="row-score">—</span></div>`).join('');}return tasks.map(t=>`<div class="task-row" data-task="${esc(t.id)}" tabindex="0" role="button"><span class="time">${time(t.sent)}</span><div class="task-name"><span class="category-icon">${icon(cats[t.category])}</span><div><strong>${esc(t.title)}</strong><small>${esc(t.category)}${t.skill?' · '+esc(t.skill):''} · ${esc(t.id)}</small></div></div>${status(t.status)}<span class="row-score">${t.score===null?'—':t.score+'<span>/100</span>'}</span></div>`).join('')||'<div class="empty-table">Chưa có bài trong ngày này.</div>';}
function overview(){const s=state.stats,c=state.settings,approved=c.approved;const nextSeq=state.next_sequence||1;const next=state.schedule[(nextSeq-1)%24];
 return heading('Một giờ tập trung. <em>Một bước tiến.</em>','Lộ trình của bạn, từ những bài tập nhỏ đến những kỹ năng lớn.',datePicker())+failureNotice()+setupNotice()+statsCards()+
 `<div class="middle-grid"><div class="journey-card"><div class="journey-content"><div class="tag">${icon('spark')}${approved?'MỤC TIÊU HÔM NAY':'BẮT ĐẦU LỘ TRÌNH'}</div><h2>${approved?'Đi đều nhịp, tiến đều mỗi ngày.':'Lộ trình tốt bắt đầu<br>bằng một đề bài rõ ràng.'}</h2><p>${approved?'Hoàn thành, nhận phản hồi, sửa lỗi. Mỗi bài được lưu lại để bạn nhìn thấy mình tiến bộ.':'Chín nhóm kỹ năng. Một bài mỗi giờ.<br>Xem đề mẫu và duyệt trước khi bật lịch.'}</p><button class="btn dark" data-page="${approved?'roadmap':'samples'}">${approved?'Xem lộ trình hôm nay':'Xem & duyệt đề mẫu'}${icon('arrow')}</button></div><div class="ring" style="--progress:${Math.min(360,s.completed/24*360)}deg"><div class="ring-inside"><strong>${s.completed}<span> / 24</span></strong><span>bài hoàn thành</span></div></div></div>
 <div class="next-card"><div class="card-header"><h2>Bài tiếp theo</h2><div class="live-chip"><i></i>${c.active?'ĐANG BẬT LỊCH':'CHƯA BẬT LỊCH'}</div></div><div class="next-main"><span class="category-icon">${icon(cats[next.category])}</span><div><strong>${esc(next.category)}${next.skill?' · '+esc(next.skill):''}</strong><small>60 phút · độ khó ${c.level.toFixed(2)}×</small></div></div><p class="subtitle">${!approved?'Duyệt mẫu để xác nhận cấu trúc đề và cách chấm.':'Đề đầy đủ, đáp án và bài chấm đều có trong app.'}</p><div class="next-footer"><span>${icon('clock')} <span id="countdown">${countdown()}</span></span><button class="btn ghost small" data-page="${'roadmap'}">${'Xem lộ trình'}${icon('arrow')}</button></div></div></div>
 <div class="bottom-grid"><div><div class="section-title"><h2>Bài tập trong ngày<small>${s.sent} đề đã có trong app</small></h2><button class="btn ghost small" data-page="roadmap">Xem tất cả${icon('arrow')}</button></div><div class="panel"><div class="table-header"><span>GIỜ</span><span>BÀI TẬP</span><span>TRẠNG THÁI</span><span>ĐIỂM</span></div>${taskRows(state.tasks.slice(0,5))}</div><div class="toolbar-note">${state.tasks.length?'Bấm vào bài để xem đề, bài nộp, đáp án và nhận xét.':'Các dòng trên là thứ tự dự kiến; chưa phải đề đã có trong app.'}</div></div>
 <div><div class="section-title"><h2>Bản đồ kỹ năng<small>Theo ngày đang xem</small></h2></div><div class="panel panel-pad">${skillList()}<p class="skill-caption">Điểm chỉ xuất hiện sau khi có bài nộp và đủ bằng chứng để chấm. Livestream cân bằng giữ chân và chuyên môn.</p></div></div></div>`;
}
function countdown(){const c=state?.settings;if(!c?.active)return 'Bật lịch để bắt đầu';let left=Math.max(0,Math.ceil(c.next_due-Date.now()/1000));if(!left)return 'Đến lượt · đang xử lý';return `${Math.floor(left/3600)?Math.floor(left/3600)+'h ':''}${String(Math.floor(left%3600/60)).padStart(2,'0')}m ${String(left%60).padStart(2,'0')}s nữa`;}
function roadmap(){let tasks=state.tasks.filter(t=>filter==='Tất cả'||t.category===filter);let cards='';if(!state.tasks.length){cards=state.schedule.filter(s=>filter==='Tất cả'||s.category===filter).map(s=>`<div class="slot-card" data-page="samples"><div class="slot-top"><span>LƯỢT ${String(s.slot).padStart(2,'0')}</span><span class="category-icon">${icon(cats[s.category])}</span></div><h3>${esc(s.category)}${s.skill?' · '+esc(s.skill):''}</h3><p>Đề sẽ được tạo khi đến lượt, chưa có kết quả.</p><div class="slot-bottom">${status('planned')}<span class="muted">60 phút</span></div></div>`).join('');}else cards=tasks.map(t=>`<div class="slot-card" data-task="${esc(t.id)}" role="button" tabindex="0"><div class="slot-top"><span>${time(t.sent)} · ${esc(t.id)}</span><span class="category-icon">${icon(cats[t.category])}</span></div><h3>${esc(t.title)}</h3><p>${esc(t.category)}${t.skill?' · '+esc(t.skill):''}</p><div class="slot-bottom">${status(t.status)}<span class="row-score">${t.score??'—'}${t.score===null?'':' /100'}</span></div></div>`).join('');
 return heading('Lộ trình <em>từng ngày.</em>','Đề bài, bài nộp và phản hồi đều có một chỗ để quay lại.',datePicker())+failureNotice()+`<div class="notice">${icon('clock')}<div>Đề có trong app vào mỗi mốc giờ đúng (ví dụ 03:00, 04:00) khi máy đang bật và có mạng. AI hoặc mạng chậm có thể làm đề đến trễ. Máy ngủ/tắt sẽ tạm dừng; mở lại chỉ nhận một lượt đến hạn. Telegram chỉ báo có đề hoặc chấm xong.</div><div class="notice-actions"><button class="btn small" data-action="toggle">${icon(state.settings.active?'pause':'play')}${state.settings.active?'Tạm dừng':'Bật lịch'}</button><button class="btn primary small" data-action="now">Tạo đề ngay</button></div></div><div class="filters">${['Tất cả',...Object.keys(cats)].map(c=>`<button class="filter ${c===filter?'active':''}" data-filter="${esc(c)}">${esc(c)}</button>`).join('')}</div><div class="roadmap-grid">${cards||'<div class="empty-table">Không có bài trong nhóm này.</div>'}</div>`;
}
function progress(){const hist=state.history.slice().reverse();return heading('Tiến bộ cần <em>bằng chứng.</em>','Nhìn lại bài đã làm, lỗi đã sửa và những kỹ năng đang vững lên.',datePicker())+statsCards()+`<div class="bottom-grid"><div class="panel panel-pad"><div class="card-header"><h2>Nhịp hoàn thành mỗi ngày</h2><span class="legend"><i></i>Bài đã chấm đủ / 24</span></div>${hist.length?`<div class="history-chart">${hist.map(h=>`<div class="chart-col"><strong>${h.completed}</strong><div class="chart-bar" style="--height:${Math.min(100,h.completed/24*100)}%"></div><span>${dateLabel(h.date).slice(0,5)}</span></div>`).join('')}</div>`:'<div class="empty-progress">Biểu đồ sẽ hiện từ ngày có bài đầu tiên.</div>'}<div class="method">Tăng độ khó 10% sau mỗi chu kỳ 24 bài được chấm đủ, điểm trung bình ≥ 80/100. Nếu chưa đạt, giữ mức hiện tại và sửa lỗi. Hệ số tối đa 3×; thời lượng luôn 60 phút.</div></div><div class="panel panel-pad"><div class="card-header"><h2>Chín nhóm kỹ năng</h2><span>${dateLabel(state.date)}</span></div>${skillList()}</div></div><div class="section-title" style="margin-top:25px"><h2>Lịch sử theo ngày</h2></div><div class="panel"><table class="history-table"><thead><tr><th>Ngày</th><th>Đề đã nhận</th><th>Hoàn thành</th><th>Điểm TB</th><th>Tiến bộ so sánh</th></tr></thead><tbody>${state.history.map(h=>`<tr data-date="${esc(h.date)}"><td>${dateLabel(h.date)}</td><td>${h.sent}</td><td>${h.completed}/24</td><td>${h.average??'—'}</td><td>${h.growth===null?'Chưa đủ mẫu':(h.growth>0?'+':'')+h.growth+'%'}</td></tr>`).join('')||'<tr><td colspan="5">Chưa có lịch sử. Ứng dụng không tạo điểm minh họa.</td></tr>'}</tbody></table></div><div class="method">Tiến bộ so sánh = (điểm cùng chuẩn hôm nay / điểm ngày gần nhất − 1) × 100%. Chỉ so các nhóm có cùng kỹ năng, hệ số độ khó, tự khai không tham khảo đáp án và ít nhất 3 bài mỗi ngày; rubric cố định. Việc mở file đáp án trên Telegram không được đo tự động, nên khai báo có thể ảnh hưởng độ tin cậy. Đây là ước lượng từ AI và phần người dùng bổ sung, chưa phải phép đo năng lực chuẩn hóa. Mục tiêu +10% không phải lời bảo đảm; tăng độ khó không có nghĩa năng lực đã tăng 10%.</div>`;}
function contentTable(text){
 const blocks=String(text??'').split(/\n+/).flatMap(line=>line.split(/;\s+(?=\d+\s*[–-]\s*\d+)/)).map(s=>s.trim()).filter(Boolean);
 const rows=blocks.map(line=>line.includes('|')?line.replace(/^\||\|$/g,'').split('|').map(s=>s.trim()):[line]);
 const tabular=rows.length>1&&rows.every(r=>r.length===rows[0].length)&&rows[0].length>1;
 if(tabular){const [head,...body]=rows;return `<table class="doc-table data-table"><thead><tr>${head.map(cell=>`<th scope="col">${esc(cell)}</th>`).join('')}</tr></thead><tbody>${body.filter(r=>!r.every(cell=>/^:?-+:?$/.test(cell))).map(r=>`<tr>${r.map(cell=>`<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
 return `<table class="doc-table"><thead><tr><th scope="col">Mục</th><th scope="col">Nội dung</th></tr></thead><tbody>${blocks.map((line,i)=>{const match=line.match(/^(\d+\s*[–-]\s*\d+(?:\s*(?:phút|giây))?)\s*[:.]?\s*(.*)$/);return `<tr><th scope="row">${match?esc(match[1]):String(i+1).padStart(2,'0')}</th><td>${esc(match?match[2]:line)}</td></tr>`;}).join('')}</tbody></table>`;
}
function docSection(title,text){return `<section class="doc-section"><h3>${esc(title)}</h3>${contentTable(text)}</section>`;}
function speakingTables(d){
 const t=d.speaking_tasks;if(!t)return d.speaking_parts?docSection('BA PHẦN SPEAKING',d.speaking_parts.join('\n\n')):'';
 const questions=(title,timing,items)=>`<section class="doc-section speaking-part"><h3>${title}</h3><p class="part-timing">${timing}</p><table class="doc-table"><thead><tr><th scope="col">Câu</th><th scope="col">Examiner asks</th></tr></thead><tbody>${items.map((q,i)=>`<tr><th scope="row">${i+1}</th><td lang="en">${esc(q)}</td></tr>`).join('')}</tbody></table></section>`;
 return questions('SPEAKING · PART 1','4–5 phút · trả lời tự nhiên, không đọc bài chuẩn bị',t.part1.questions)+`<section class="doc-section speaking-part"><h3>SPEAKING · PART 2</h3><p class="part-timing">1 phút chuẩn bị · nói tối đa 2 phút · cả phần 3–4 phút</p><table class="doc-table cue-card"><tbody><tr><th scope="row">Cue card</th><td lang="en"><strong>${esc(t.part2.cue_card)}</strong></td></tr>${t.part2.bullets.map((b,i)=>`<tr><th scope="row">Gợi ý ${i+1}</th><td lang="en">${esc(b)}</td></tr>`).join('')}${t.part2.followups.map((q,i)=>`<tr><th scope="row">Follow-up ${i+1}</th><td lang="en">${esc(q)}</td></tr>`).join('')}</tbody></table></section>`+questions('SPEAKING · PART 3','4–5 phút · giải thích, phân tích và đối chiếu ví dụ',t.part3.questions);
}
function livestreamTables(d){
 if((d.category||task?.category)!=='Livestream')return '';
 const plans=[['Chuyên môn',d.livestream_expertise,d.expertise_element,'Nội dung & lời dẫn','Kiểm tra hiểu biết'],['Giữ chân',d.livestream_retention,d.retention_element,'Hoạt động & lời dẫn','Theo dõi & phương án dự phòng']];
 return `<div class="livestream-plans">${plans.map(([name,rows,anchor,action,check])=>rows?.length?`<section class="live-plan"><h3>${esc(name)}</h3><p class="live-anchor">${esc(anchor)}</p><table><caption>Kịch bản ${esc(name.toLowerCase())} theo phút</caption><thead><tr><th scope="col">Phút</th><th scope="col">${action}</th><th scope="col">${check}</th></tr></thead><tbody>${rows.map(row=>`<tr><th scope="row">${esc(row.time)}</th><td><strong>${esc(row.focus)}</strong><div>${esc(row.script)}</div></td><td>${esc(row.check)}</td></tr>`).join('')}</tbody></table></section>`:'').join('')}</div>`;
}
function docBody(d,withAnswer=false){if(d.reading_passages)d={...d,materials:d.materials+'\n\n'+d.reading_passages.join('\n\n')};const chart=d.chart_image?`<figure class="assignment-chart"><img src="${esc(d.chart_image)}" alt="${esc(d.chart?.title||'Biểu đồ Writing Task 1')}" loading="eager"><figcaption>Biểu đồ vẽ chính xác từ số liệu của đề · dữ liệu thực hành, không phải thống kê công bố. Bấm ảnh để xem lớn.</figcaption></figure>`:'';return `<div class="document"><div class="doc-kicker">${esc(d.category||task?.category||'BÀI THỰC HÀNH')} ${esc(d.skill||task?.skill||'')} · 60 PHÚT</div><h2>${esc(d.title)}</h2>${chart}${docSection('01 · MỤC TIÊU',d.objective)}${docSection('02 · DỮ LIỆU & NGUYÊN LIỆU',d.materials)}${docSection('03 · CÁCH LÀM & PHÂN BỔ THỜI GIAN',d.instructions)}${livestreamTables(d)}${d.writing_tasks?docSection('HAI TASK WRITING',d.writing_tasks.join('\n\n')):''}${speakingTables(d)}${d.questions?docSection('CÂU HỎI',d.questions.map(q=>`${q.number}. ${q.question}`).join('\n\n')):''}${docSection('04 · BÀI CẦN NỘP',d.deliverables)}<section class="doc-section"><h3>05 · THANG CHẤM 100 ĐIỂM</h3><table class="rubric-table">${d.rubric.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.max_score} điểm</td></tr>`).join('')}</table></section>${withAnswer?`<details class="answer-details"><summary>Xem đáp án tham khảo của đề mẫu</summary><div class="doc-text">${esc(d.answer_key)}</div></details>`:''}</div>`;}
function samplesPage(){const d=sampleData[sampleIndex];if(!d)return '<div class="loading">Đang tải đề mẫu…</div>';return heading('Đề đầy đủ. <em>Bạn duyệt trước.</em>','Xem mẫu của cả chín nhóm, gồm Writing và Speaking đầy đủ; duyệt rồi bật lịch tại giờ tròn.',`<button class="btn" data-action="preview">${icon('spark')}Tạo mẫu Writing bằng AI</button>`)+failureNotice()+`<div class="notice">${icon('document')}<div><strong>${esc(d.source||'Mẫu biên soạn sẵn')}</strong><br>IELTS mỗi ngày có đủ bốn kỹ năng qua các lượt riêng. Listening: 4 section/40 câu có audio; Reading: 3 passage/40 câu; Writing: 2 task; Speaking: 3 part. Bài mẫu dưới đây là một lượt 60 phút.</div></div><div class="sample-layout"><div class="sample-nav">${sampleData.map((s,i)=>`<button class="sample-button ${i===sampleIndex?'active':''}" data-sample="${i}">${icon(cats[s.category])}${esc(s.category+(s.category==='IELTS'?' · '+s.skill:''))}</button>`).join('')}<div class="sample-nav-footer">${state.settings.approved?'✓ Bạn đã duyệt cấu trúc đề.':'Lịch vẫn tắt cho đến khi bạn duyệt.'}</div></div><div>${docBody(d,true)}<div class="approve-panel"><div><strong>${state.settings.approved?'Cấu trúc đã được duyệt':'Bạn duyệt cấu trúc và mức chi tiết này?'}</strong><p>Đề có dữ liệu, bước làm, đầu ra, rubric và đáp án. Duyệt để nhận đề trong app tại mốc đầu giờ kế tiếp. Telegram không bắt buộc.</p></div><button class="btn primary" data-action="approve">${icon('check')}${state.settings.approved?'Bật lịch đầu giờ':'Duyệt mẫu & bắt đầu'}</button></div></div></div>`;}
function settingsPage(){
 const c=state.settings;
 const botLink=c.telegram_username?`https://t.me/${encodeURIComponent(c.telegram_username)}?start=${encodeURIComponent(c.pairing_code)}`:'';
 return heading('Thiết lập một lần. <em>Tập mỗi giờ.</em>','Làm bài và xem đánh giá trên laptop. Telegram chỉ nhận thông báo.')+setupNotice()+
 `<div class="notice">${icon('document')}<div><strong>Luồng chính của bạn</strong><br>Đề mới → làm và lưu ở cuối đề → hoàn thành đủ 12 đề → Gửi tất cả & chấm → nhận kết quả cả bộ. Đóng tab vẫn chạy nền; nút dừng nằm ở đầu màn hình.</div><div class="notice-actions"><button class="btn primary small" data-page="samples">Xem & duyệt mẫu</button></div></div>`+
 codexSettings()+`<div class="settings-grid"><div><form id="settings-form">
 <div class="settings-box"><h2>${icon('send')}Thông báo Telegram · tùy chọn</h2><p>Bot báo có đề mới hoặc chấm xong cả bộ 12 đề. Đề, đáp án, bài làm và nhận xét đầy đủ nằm trong app. Bạn vẫn tập bình thường khi chưa tạo bot.</p>
 <div class="field"><label for="telegram-token">Bot token<span>${c.telegram_token_set?'✓ Đã lưu an toàn':'Chưa lưu'}</span></label><input id="telegram-token" name="telegram_token" type="password" autocomplete="new-password" placeholder="${c.telegram_token_set?'Để trống để giữ bot hiện tại':'Token nhận từ BotFather sau /newbot'}"><small>Chỉ dán token trong ô này; không đưa vào GitHub hoặc gửi trong chat.</small></div>
 <div class="settings-actions"><button class="btn primary" type="submit">Lưu bot & cấu hình${icon('check')}</button><span class="muted">${c.telegram_chat_id?'✓ Đã ghép tài khoản':'Chưa ghép tài khoản'}</span></div>
 <ol class="steps" style="margin-top:22px"><li><span class="step-num">1</span><div><strong>Tạo bot</strong><br>Mở <a href="https://t.me/BotFather" target="_blank" rel="noreferrer">@BotFather</a> → /newbot → đặt tên và username. Dán token phía trên rồi Lưu.</div></li>
 <li><span class="step-num">2</span><div><strong>Mở bot và bấm Start</strong><br>${c.telegram_chat_id?'✓ Đã ghép. Chỉ tài khoản này nhận thông báo.':botLink?`<a class="btn primary small" href="${botLink}" target="_blank" rel="noreferrer">Mở @${esc(c.telegram_username)} & bấm Start</a>`:'Nút mở bot xuất hiện sau khi bạn lưu token hợp lệ.'}
 ${!c.telegram_chat_id?`<div class="pairing"><code>/start ${esc(c.pairing_code)}</code><button type="button" class="btn small" data-action="copy-pair" aria-label="Sao chép lệnh ghép Telegram">${icon('copy')}Sao chép</button></div><button type="button" class="btn small" data-action="refresh-pair">Đã bấm Start · kiểm tra ghép</button>`:''}</div></li>
 <li><span class="step-num">3</span><div><strong>Thử thông báo</strong><br><button type="button" class="btn small" data-action="test-telegram" ${c.telegram_chat_id?'':'disabled'}>Gửi thông báo thử</button></div></li></ol></div>
 <div class="settings-box"><h2>${icon('book')}Mục tiêu IELTS & audio</h2>
 <div class="field-row"><div class="field"><label for="band">IELTS hiện tại</label><input id="band" name="band" type="number" min="0" max="9" step="0.5" value="${c.band}"></div><div class="field"><label for="goal-band">Mục tiêu IELTS</label><input id="goal-band" name="goal_band" type="number" min="0.5" max="9" step="0.5" value="${c.goal_band}"></div></div>
 <details><summary>Cấu hình chép lời Speaking</summary><p>Chép lời bằng faster-whisper trên laptop. Phát âm cần người nghe xác minh.</p><div class="field"><label for="speech-python">Python đã cài bộ chép lời</label><input id="speech-python" name="speech_python" value="${esc(c.speech_python)}" placeholder="Chạy INSTALL-SPEECH.ps1 trước"></div><div class="field"><label for="speech-model">Model CPU</label><select id="speech-model" name="speech_model">${['tiny','base','small'].map(m=>`<option ${m===c.speech_model?'selected':''}>${m}</option>`).join('')}</select></div></details>
 <button class="btn" type="submit">Lưu mục tiêu & audio</button></div>
 <details class="settings-box"><summary>Antigravity · cấu hình nâng cao</summary><p>Chỉ dùng khi chọn Antigravity làm nguồn AI.</p><div class="field"><label for="gateway-url">Địa chỉ API</label><input id="gateway-url" name="gateway_url" value="${esc(c.gateway_url)}" required></div><div class="field"><label for="gateway-key">API key<span>${c.gateway_key_set?'✓ Đã lưu':'Chưa lưu'}</span></label><input id="gateway-key" name="gateway_key" type="password" autocomplete="new-password" placeholder="Để trống để giữ key hiện tại"></div><button class="btn" type="submit">Lưu Antigravity</button></details>
 </form></div><div>
 <div class="settings-box"><h2>${icon('document')}Nộp bài ngay trong app</h2><ol class="steps"><li><span class="step-num">1</span><div>Mở <strong>Lộ trình mỗi ngày</strong>, chọn đúng đề.</div></li><li><span class="step-num">2</span><div>Vào <strong>Bài nộp</strong>, dán bài hoặc đính kèm DOCX, TXT, ảnh, audio; chọn đã tham khảo đáp án hay chưa.</div></li><li><span class="step-num">3</span><div>Bấm <strong>Lưu bài làm</strong> ở cuối từng đề. Đủ 12 đề → <strong>Bộ bài & chấm</strong> → <strong>Gửi tất cả & chấm</strong>. Kết quả hiện cùng lúc dưới ô bài làm và trong trang bộ bài.</div></li></ol><p>Video ≤100 MB / 30 phút; file khác ≤20 MB, mỗi bài ≤40 ảnh và 120.000 ký tự sau trích xuất. Google Docs hiện chưa kết nối; xuất DOCX nếu muốn nộp tài liệu có chữ và ảnh.</p><button class="btn" data-page="roadmap">Mở lộ trình${icon('arrow')}</button></div>
 <div class="settings-box"><h2>${icon('settings')}Chạy nền trên Windows</h2><p>Đóng tab vẫn tạo đề và chấm bài. Shortcut Startup mở app khi đăng nhập Windows. Máy phải đang chạy và có mạng để gọi Codex.</p><p>Tạm dừng bằng nút đầu trang; thoát hoàn toàn bằng chuột phải biểu tượng Hourly Coach trong khay hệ thống → Thoát ứng dụng.</p><div class="field"><label>Dữ liệu trên laptop</label><div class="doc-text">${esc(state.data_path)}</div></div><p>Key/token được mã hóa bằng Windows DPAPI. Sao lưu thư mục data khi app đã thoát; không đưa data lên GitHub.</p><div class="activity-card"><strong>Hoạt động gần đây</strong>${state.events.slice(0,6).map(e=>`<div class="event"><time>${time(e.created)}</time><span>${esc(e.message)}</span></div>`).join('')||'<p class="muted">Chưa có hoạt động.</p>'}</div></div>
 </div></div>`;
}
async function refresh(force=false){if(rendering)return;try{const data=await api('/api/state'+(selectedDate?'?date='+encodeURIComponent(selectedDate):''));if(page==='batches'&&batchCycle)data.batch=await api('/api/batch?cycle='+batchCycle);state=data;selectedDate=data.date;const fingerprint=JSON.stringify([page,data.tasks,data.stats,data.settings,data.failures,data.delivery_issues,data.codex_requests,data.events,data.activity,data.batch,data.batch_history]);if(force||fingerprint!==lastFingerprint){lastFingerprint=fingerprint;if(page==='samples')sampleData=(await api('/api/samples')).samples;if(page!=='settings'||force)render();}$('#connection').className='connection'+(health.online?'':' off');$('#connection').innerHTML=`<i></i>${health.online?(health.model?'Codex · '+esc(health.model):'Gateway đang mở'):'Gateway chưa xác nhận'}`;$('.sidebar-note strong').textContent=`${data.settings.band} → ${data.settings.goal_band}`;if(data.activity!=='Sẵn sàng')$('#connection').innerHTML=`<i></i>${esc(data.activity)}`;const el=$('#countdown');if(el)el.textContent=countdown();}catch(e){if(force)toast(e.message,true);}}
function render(){if(!state)return;$('#page-name').textContent=pageNames[page];$('#auto-toggle').innerHTML=icon(state.settings.active?'pause':'play')+(state.settings.active?'Dừng tạo đề tự động':'Bật tạo đề tự động');$('#auto-toggle').className='btn small '+(state.settings.active?'danger':'primary');document.querySelectorAll('#navigation .nav-item,.sidebar-bottom .nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const funcs={overview,roadmap,progress,samples:samplesPage,batches:batchPage,settings:settingsPage};$('#content').innerHTML=funcs[page]();document.querySelectorAll('[data-icon]').forEach(n=>n.innerHTML=icon(n.dataset.icon));}
async function navigate(p){if(task)closeModal();page=p;location.hash=p;if(p==='samples'){const result=await api('/api/samples');sampleData=result.samples;}render();window.scrollTo(0,0);}
async function openTask(id){try{task=await api('/api/task?id='+encodeURIComponent(id));modalTab='assignment';uploaded=[];modalPreviousFocus=document.activeElement;renderModal();$('#modal').classList.remove('hidden');document.body.classList.add('modal-open');$('#modal .modal-close').focus();}catch(e){toast(e.message,true);}}
function renderModal(){const tabs=[['assignment','Đề bài'],['submission','Bài nộp'],['evaluation','Đánh giá'],['answers','Đáp án']];$('#modal').innerHTML=`<div class="modal-panel"><div class="modal-header"><button class="modal-close" data-action="close-modal" aria-label="Đóng chi tiết">×</button><h2>${esc(task.title)}</h2><span class="muted">${esc(task.id)} · ${esc(task.category)} ${esc(task.skill)} · ${status(task.status)}</span><div class="modal-tabs">${tabs.map(([key,label])=>`<button class="modal-tab ${modalTab===key?'active':''}" data-tab="${key}">${label}</button>`).join('')}</div></div><div class="modal-body">${modalContent()}</div></div>`;}
function modalContent(){
 if(modalTab==='assignment')return (task.audio.length?`<div class="audio-list"><strong>Listening · audio của đề</strong>${task.audio.map(a=>`<div class="audio-item">${esc(a.name)}<audio controls preload="none" src="${esc(a.url)}"></audio></div>`).join('')}</div>`:'')+docBody(task.body)+workflowPanel(task);
 if(modalTab==='submission')return workflowPanel(task);
 if(modalTab==='evaluation')return evaluationPanel(task.evaluation)+(!task.evaluation?.complete&&task.evaluation?`<form id="verify-form" class="verify-form"><h3>Bổ sung tiêu chí cần người kiểm tra</h3><p>Nhờ người nghe/xem bản ghi thực tế. Nếu tự chấm, ghi rõ nguồn.</p>${task.evaluation.criteria.map((r,i)=>r.score===null?`<div class="field"><label>${esc(r.name)} (0–${r.max_score})</label><input name="criterion_${i}" type="number" min="0" max="${r.max_score}" step="0.5" required></div>`:'').join('')}<div class="field"><label>Ai kiểm tra và bằng chứng</label><textarea name="note" minlength="15" required></textarea></div><button class="btn primary" type="submit">Lưu đánh giá bổ sung</button></form>`:'');
 return `<div class="document"><h2>Đáp án & bài tham khảo</h2>${docSection('FULL ĐÁP ÁN',task.answer_key)}${task.answers?docSection('40 CÂU — ĐÁP ÁN VÀ GIẢI THÍCH',task.answers.map(q=>`${q.number}. ${q.answer}\n${q.explanation}`).join('\n\n')):''}${task.transcripts?docSection('TRANSCRIPT LISTENING',task.transcripts.join('\n\n')):''}</div>`;
}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').innerHTML='';document.body.classList.remove('modal-open');task=null;modalPreviousFocus?.focus();}
async function perform(action,button){if(button)button.disabled=true;try{let result;
 if(action==='today'){selectedDate=state.today;await refresh(true);return;}
 if(action==='health'){health=await api('/api/health');toast(health.online?(health.model?'Đã nối Codex · '+health.model:'Gateway đang mở. Phản hồi AI còn phụ thuộc relay.'):(health.error||'Chưa kết nối được gateway.'),!health.online);await refresh(true);return;}
 if(action==='copy-pair'){await navigator.clipboard.writeText('/start '+state.settings.pairing_code);toast('Đã sao chép lệnh ghép Telegram.');return;}
 if(action==='close-modal'){closeModal();return;}
 if(action==='refresh-task'){task=await api('/api/task?id='+encodeURIComponent(task.id));renderModal();return;}
 if(action==='approve'){result=await api('/api/approve',{});toast(result.message||'Đã duyệt. Lịch bắt đầu tại mốc đầu giờ kế tiếp.');}
 if(action==='submit-batch'){const cycle=Number(button?.dataset.cycle||task?.batch.cycle||state.batch.cycle);await api('/api/batch/submit',{cycle,request_id:crypto.randomUUID().replace(/-/g,'')});toast('Đã gửi trọn bộ 12 đề. Kết quả mở cùng lúc sau khi chấm hết.');if(task){task=await api('/api/task?id='+encodeURIComponent(task.id));renderModal();}batchCycle=cycle;}
 if(action==='toggle'){await api('/api/toggle',{});toast(state.settings.active?'Đã tạm dừng tạo đề.':'Đã bật lịch. Đề đầu tiên có trong app tại mốc đầu giờ kế tiếp.');}
 if(action==='refresh-pair'){await refresh(true);toast(state.settings.telegram_chat_id?'Đã ghép Telegram. Bạn có thể thử thông báo.':'Chưa nhận Start. Mở bot, bấm Start rồi kiểm tra lại.');return;}
 if(action==='test-telegram'){await api('/api/telegram/test',{});toast('Đã xếp hàng gửi thông báo thử. Xem Telegram hoặc log nếu có lỗi.');}
 if(action==='preview'){await api('/api/preview',{});toast('Đã xếp hàng tạo mẫu Writing bằng nguồn AI bạn đã chọn. Phản hồi có thể mất vài phút.');}
 if(action==='send-sample'){await api('/api/sample',{});toast('Đề mẫu đang được gửi đến Telegram đã ghép.');}
 if(action==='now'){await api('/api/now',{});toast('Đang tạo một đề đầy đủ trong app bằng nguồn AI bạn đã chọn.');}
 if(action==='retry'){await api('/api/retry',{});toast('Đã đưa tác vụ lỗi vào hàng đợi thử lại.');}
 if(action==='retry-uncertain'){if(!window.confirm('Tin này có thể đã đến Telegram. Bạn đã kiểm tra và muốn gửi lại? Có thể tạo tin trùng.'))return;await api('/api/retry',{include_uncertain:true});toast('Đã xếp hàng gửi lại các tin chưa xác định.');}
 await refresh(true);if(page==='samples'){sampleData=(await api('/api/samples')).samples;render();}
 }catch(e){toast(e.message,true);}finally{if(button?.isConnected)button.disabled=false;}}
document.addEventListener('click',async e=>{const target=e.target.closest('[data-page],[data-action],[data-task],[data-filter],[data-sample],[data-tab],[data-date]');if(!target)return;try{if(target.dataset.page){e.preventDefault();await navigate(target.dataset.page);}else if(target.dataset.action){e.preventDefault();await perform(target.dataset.action,target);}else if(target.dataset.task)await openTask(target.dataset.task);else if(target.dataset.filter){filter=target.dataset.filter;render();}else if(target.dataset.sample){sampleIndex=Number(target.dataset.sample);render();}else if(target.dataset.tab){modalTab=target.dataset.tab;if(modalTab==='answers'){await api('/api/answers',{id:task.id});task.answer_viewed=Date.now()/1000;}renderModal();}else if(target.dataset.date){selectedDate=target.dataset.date;page='roadmap';await refresh(true);}}catch(err){toast(err.message,true);}});
document.addEventListener('change',async e=>{if(e.target.id==='date-picker'){selectedDate=e.target.value;await refresh(true);}if(e.target.id==='submission-files')$('#upload-status').textContent=[...e.target.files].map(f=>`${f.name} (${(f.size/1048576).toFixed(1)} MB)`).join(' · ');});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if((e.key==='Enter'||e.key===' ')&&e.target.dataset.task){e.preventDefault();openTask(e.target.dataset.task);}if(e.key==='Tab'&&!$('#modal').classList.contains('hidden')){const focusable=[...$('#modal').querySelectorAll('button,a,input,textarea,select,audio')].filter(n=>!n.disabled);const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal();});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target;if(form.id==='codex-form'||form.id==='codex-chat-form')return;const button=form.querySelector('button[type=submit]');button.disabled=true;rendering=true;try{
 if(form.id==='settings-form'){const values=Object.fromEntries(new FormData(form));const result=await api('/api/settings',values);toast(result.warning||'Đã lưu cấu hình an toàn.',Boolean(result.warning));}
 if(form.id==='draft-form'){
  const files=[...form.querySelector('#submission-files').files],kept=[...form.querySelectorAll('[name=keep_file]:checked')].map(e=>e.value);if(files.length+kept.length>40)throw new Error('Tối đa 40 file/lượt.');
  const paths=[...kept];for(let i=0;i<files.length;i++){const file=files[i],video=/\.(mp4|mov|webm|mkv)$/i.test(file.name),limit=video?100:20;if(file.size>limit*1048576)throw new Error(file.name+' vượt '+limit+' MB.');form.querySelector('#upload-status').textContent=`Đang lưu file ${i+1}/${files.length}: ${file.name}`;const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const result=await api('/api/upload',{name:file.name,data:encoded});paths.push(result.path);}
  await api('/api/draft',{id:form.dataset.taskId,text:form.elements.text.value,files:paths,assistance:form.elements.assistance.value,complete:form.elements.complete.checked});toast('Đã lưu bài làm. Chưa gửi đi chấm; cần hoàn thành đủ 12 đề.');task=await api('/api/task?id='+encodeURIComponent(form.dataset.taskId));renderModal();
 }
 if(form.id==='verify-form'){const values=Object.fromEntries(new FormData(form)),scores={};for(const [key,value] of Object.entries(values))if(key.startsWith('criterion_'))scores[key.slice(10)]=Number(value);await api('/api/verify',{id:task.id,scores,note:values.note});toast('Đã lưu nguồn điểm bổ sung.');task=await api('/api/task?id='+encodeURIComponent(task.id));renderModal();}
 }catch(err){toast(err.message,true);}finally{rendering=false;if(button.isConnected)button.disabled=false;await refresh(form.id==='settings-form');}});
setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString('vi-VN',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit'});const el=$('#countdown');if(el&&state)el.textContent=countdown();},1000);
setInterval(()=>{refresh();refreshInlineResults();},5000);
async function init(){document.querySelectorAll('[data-icon]').forEach(n=>n.innerHTML=icon(n.dataset.icon));try{health=await api('/api/health');page=pageNames[location.hash.slice(1)]?location.hash.slice(1):'overview';if(page==='samples')sampleData=(await api('/api/samples')).samples;await refresh(true);}catch(e){$('#content').innerHTML=`<div class="notice error">${esc(e.message)}</div>`;}}
document.addEventListener('click',e=>{if(e.target.matches('.assignment-chart img'))window.open(e.target.src,'_blank','noopener');});
init();
