'use strict';
let batchCycle=0;

function evaluationPanel(e){
 if(!e)return '<div class="notice">Kết quả sẽ hiện tại đây sau khi cả bộ 12 đề đã chấm xong.</div>';
 return `<div class="grade-total"><strong>${e.complete?e.score+' /100':'Cần thêm bằng chứng'}</strong><p>${e.complete?'Đã chấm đủ tiêu chí':'Điểm quan sát được: '+e.observed_points+' · chưa là tổng điểm'}</p></div><div class="document result-document">${docSection('NHẬN XÉT CHUNG',e.summary)}<table class="doc-table data-table"><thead><tr><th>Tiêu chí</th><th>Điểm</th><th>Nhận xét</th></tr></thead><tbody>${e.criteria.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.score??'Chưa chấm'} / ${r.max_score}</td><td>${esc(r.feedback)}</td></tr>`).join('')}</tbody></table>${docSection('SỬA LỖI CHI TIẾT',e.corrections)}${docSection('BÀI MẪU ĐẦY ĐỦ',e.model_answer)}${docSection('VIỆC CẦN LÀM TIẾP',e.next_steps)}${docSection('GIỚI HẠN CỦA ĐÁNH GIÁ',e.evidence_limits)}</div>`;
}

function batchGate(b){
 const running=b.batch&&['queued','running'].includes(b.batch.status);
 return `<div class="batch-gate"><strong>Bộ ${b.cycle} · ${b.complete}/12 bài đã hoàn thành</strong><p>${running?`Đang chấm ${b.graded_count}/12 bài. Kết quả mở cùng lúc khi chấm hết. Bạn vẫn có thể làm đề cũ hoặc đề tiếp theo.`:b.batch?.status==='failed'?'Có bài chấm lỗi. Bài đã được lưu; bấm Thử lại để tiếp tục.':b.can_submit?'Đã đủ 12 bài. Gửi trọn bộ khi bạn sẵn sàng.':`Đã nhận ${b.available}/12 đề. Cần đủ 9 nhóm và 4 kỹ năng IELTS trước khi gửi.`}</p><button type="button" class="btn primary" data-action="submit-batch" data-cycle="${b.cycle}" ${b.can_submit?'':'disabled'}>${icon('send')}${b.batch&&['graded','needs_evidence'].includes(b.batch.status)?'Gửi lại cả bộ & chấm':'Gửi tất cả & chấm'} · 12 đề</button>${b.batch?.status==='failed'?'<button type="button" class="btn" data-action="retry">Thử lại các bài lỗi</button>':''}<button type="button" class="btn" data-page="batches">Xem cả bộ</button></div>`;
}

function workflowPanel(t){
 const d=t.draft||{text:'',files:[],complete:false,assistance:'unknown'};
 const locked=t.batch?.batch&&['queued','running','failed'].includes(t.batch.batch.status);
 if(!t.sent)return '<div class="notice">Đề đang chuẩn bị. Ô bài làm mở khi đề được phát vào giờ đến hạn.</div>';
 return `<section class="work-panel"><h2>Bài làm của bạn · ${esc(t.id)}</h2><p>Dán text hoặc đính kèm ảnh, video, DOCX và audio cho đúng đề này. Lưu nháp để làm dần; chưa chấm cho đến khi cả bộ đủ 12 bài.</p><form id="draft-form" data-task-id="${esc(t.id)}"><fieldset ${locked?'disabled':''}><div class="field"><label for="submission-text">Nội dung bài làm</label><textarea id="submission-text" name="text" placeholder="Dán bài làm, ghi chú hoặc giải thích cho video/ảnh…">${esc(d.text)}</textarea></div><div class="field"><label for="assistance">Bạn có tham khảo đáp án trước khi làm không?</label><select id="assistance" name="assistance"><option value="unknown" ${d.assistance==='unknown'?'selected':''}>Chưa khai báo</option><option value="no" ${d.assistance==='no'?'selected':''}>Không — tôi tự làm</option><option value="yes" ${d.assistance==='yes'?'selected':''}>Có — dùng đáp án để học</option></select></div><div class="submit-drop"><label for="submission-files">Đính kèm text, ảnh, video, DOCX hoặc audio</label><input id="submission-files" type="file" multiple accept=".docx,.txt,.png,.jpg,.jpeg,.webp,.mp3,.wav,.m4a,.ogg,.flac,.mp4,.mov,.webm,.mkv"><small>Video ≤100 MB, ≤30 phút; file khác ≤20 MB. Video được phân tích qua tối đa 12 frame có timecode và transcript âm thanh.</small><div id="upload-status" class="file-preview"></div></div><div class="saved-files">${d.files.map((f,i)=>`<label><input type="checkbox" name="keep_file" value="${esc(f.path)}" checked>Giữ ${esc(f.name)}</label>`).join('')||'<span class="muted">Chưa có file đã lưu.</span>'}</div><label class="completion-check"><input type="checkbox" name="complete" ${d.complete?'checked':''}> Tôi đã làm xong đề này</label><button class="btn primary" type="submit">${icon('check')}Lưu bài làm</button><p class="draft-note">Lưu bài không gửi đi chấm. Đánh dấu hoàn thành sau khi đã nộp đủ phần của đề.</p></fieldset></form><div class="inline-batch-gate">${batchGate(t.batch)}</div><div class="inline-results" aria-live="polite"><h2>Kết quả đánh giá của đề này</h2>${evaluationPanel(t.evaluation)}</div><details class="answer-details"><summary>Các bản bài đã gửi trong bộ</summary>${t.submissions.map(s=>`<article class="submission"><strong>${time(s.created)} · ${esc(labels[s.status]||s.status)}</strong>${s.error?`<p class="notice error">${esc(s.error)}</p>`:''}<div class="doc-text">${esc(s.text)}</div><div class="file-links">${s.files.map(f=>`<a class="file-link" href="${esc(f.url)}" target="_blank" rel="noreferrer">${esc(f.name)}</a>`).join('')}</div>${s.evaluation?evaluationPanel(s.evaluation):'<p>Kết quả của bộ chưa mở.</p>'}</article>`).join('')||'<p>Chưa gửi bộ bài nào.</p>'}</details></section>`;
}

function batchPage(){
 const b=state.batch;
 return heading('Hoàn thành cả bộ. <em>Nhận chấm một lượt.</em>','12 đề: chín nhóm, IELTS đủ Listening · Reading · Writing · Speaking.')+failureNotice()+(state.settings.active?`<p class="part-timing">${icon('clock')}Đề tiếp theo lúc <strong>${time(state.settings.next_due)}</strong> · nếu AI/mạng chậm, app ghi trạng thái xử lý.</p>`:'')+batchGate(b)+`<div class="panel panel-pad"><h2>Bộ ${b.cycle} · bài đã lưu tại máy</h2><table class="doc-table data-table batch-table"><thead><tr><th>Đề</th><th>Loại bài</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>${b.items.map(r=>`<tr><td>${r.slot}</td><td><strong>${esc(r.category)} ${esc(r.skill)}</strong><small>${esc(r.title)}</small></td><td>${r.complete?'✓ Hoàn thành':r.has_draft?'Đang làm':r.available?'Chưa làm':'Chưa đến giờ'}</td><td>${r.available?`<button class="btn small" data-task="${esc(r.id)}">${r.has_draft?'Tiếp tục':'Làm bài'}</button>`:'—'}</td></tr>`).join('')}</tbody></table></div><section class="batch-results"><h2>Kết quả của cả bộ</h2>${b.results.length?b.results.map(r=>`<details class="batch-result"><summary>${esc(r.id)} · ${esc(r.category)} ${esc(r.skill)} · ${r.evaluation.complete?r.evaluation.score+'/100':'Cần bằng chứng'}</summary>${evaluationPanel(r.evaluation)}<button class="btn" data-task="${esc(r.id)}">Mở đề và bài đã gửi</button></details>`).join(''):'<div class="notice">Kết quả xuất hiện cùng lúc sau khi cả 12 bài đã được chấm. Nếu một bài chấm lỗi, app giữ cả bộ và cho thử lại.</div>'}</section><div class="section-title"><h2>Lịch sử bộ bài</h2></div><div class="filters">${state.batch_history.map(r=>`<button class="btn small" data-batch-cycle="${r.cycle}">Bộ ${r.cycle} · ${esc(labels[r.status]||r.status)}</button>`).join('')||'<p class="muted">Chưa gửi bộ bài nào.</p>'}</div>`;
}

async function refreshInlineResults(){
 if(!task||rendering)return;
 try{const updated=await api('/api/task?id='+encodeURIComponent(task.id));if(!task||task.id!==updated.id)return;task.evaluation=updated.evaluation;task.batch=updated.batch;task.submissions=updated.submissions;const results=$('.inline-results');if(results)results.innerHTML='<h2>Kết quả đánh giá của đề này</h2>'+evaluationPanel(updated.evaluation);const gate=$('.inline-batch-gate');if(gate)gate.innerHTML=batchGate(updated.batch);const fieldset=$('#draft-form fieldset');if(fieldset)fieldset.disabled=Boolean(updated.batch.batch&&['queued','running','failed'].includes(updated.batch.batch.status));}catch(e){}
}
document.addEventListener('click',async e=>{const button=e.target.closest('[data-batch-cycle]');if(!button)return;batchCycle=Number(button.dataset.batchCycle);await navigate('batches');await refresh(true);});
